package pt.ipleria.estg.dei.ei.dae.academics.ejbs;

import jakarta.ejb.Stateless;
import jakarta.json.*;
import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.logging.Logger;

@Stateless
public class AiSummaryBean {

    private static final Logger LOG =
            Logger.getLogger(AiSummaryBean.class.getName());

    private static final String OLLAMA_URL =
            "http://host.docker.internal:11434/api/generate";

    private static final String MODEL = "llama3";

    public String generateSummary(String text) {

        if (text == null || text.isBlank()) {
            LOG.warning("Text is null or empty");
            return null;
        }

        try {
            String prompt =
                    "És um assistente académico. Cria um resumo curto, claro e objetivo "
                            + "de uma publicação científica com base na informação seguinte:\n\n"
                            + text;

            JsonObject payload = Json.createObjectBuilder()
                    .add("model", MODEL)
                    .add("prompt", prompt)
                    .add("stream", false)
                    .build();

            HttpURLConnection conn =
                    (HttpURLConnection) new URL(OLLAMA_URL).openConnection();

            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json");
            conn.setDoOutput(true);

            try (OutputStream os = conn.getOutputStream()) {
                os.write(payload.toString()
                        .getBytes(StandardCharsets.UTF_8));
            }

            int responseCode = conn.getResponseCode();
            LOG.info("Ollama response code: " + responseCode);

            InputStream is = (responseCode < 400)
                    ? conn.getInputStream()
                    : conn.getErrorStream();

            String responseBody =
                    new String(is.readAllBytes(), StandardCharsets.UTF_8);

            if (responseCode >= 400) {
                LOG.severe("Ollama error: " + responseBody);
                return null;
            }

            try (JsonReader reader =
                         Json.createReader(new StringReader(responseBody))) {

                JsonObject json = reader.readObject();
                String summary = json.getString("response").trim();

                LOG.info("Summary generated by Ollama");
                return summary;
            }

        } catch (Exception e) {
            LOG.severe("Erro ao gerar resumo com Ollama: " + e.getMessage());
            return null;
        }
    }
}
